First commit

diff --git a/linepush b/linepush
--- a/linepush
+++ b/linepush
@@ -21,9 +21,12 @@ if [ -z "$message" ]; then
     exit 1
 fi
 
-curl -X POST https://api.line.me/v2/bot/message/push \
+response=$(curl -s -X POST https://api.line.me/v2/bot/message/push \
      -H "Content-Type: application/json" \
      -H "Authorization: Bearer ${LINEPUSH_CHANNEL_ACCESS_TOKEN}" \
-     -d "{\"to\":\"${LINEPUSH_USER_ID}\",\"messages\":[{\"type\":\"text\",\"text\":\"$message\"}]}"
+     -d "{\"to\":\"${LINEPUSH_USER_ID}\",\"messages\":[{\"type\":\"text\",\"text\":\"$message\"}]}")
 
-echo ""
+if [ "$response" != "{}" ]; then
+    echo "Error: $response"
+    exit 1
+fi
